apiVersion: v1
kind: Service
metadata:
  name: node-app-service # name of the service 
spec:
  type: LoadBalancer
  selector:
    app: node-app # selects all nodes with this selector name mentioned in the template of the deployment. 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
